apiVersion: apps/v1
kind: Deployment
metadata:
  name: {name}
  namespace: {namespace}
spec:
  replicas: {replicas}
  selector:
    matchLabels:
      app: {name}
  template:
    metadata:
      labels:
        app: {name}
        ns: {namespace}
    spec:
      containers:
      - name: executor
        image: {image}
        imagePullPolicy: {pull_policy}
        command: {command}
        args: {args}
        ports:
          - containerPort: {port_expose}
          - containerPort: {port_in}
          - containerPort: {port_out}
          - containerPort: {port_ctrl}
        livenessProbe:
          exec:
            command:
              - python
              - from jina.peapods.runtimes.grpc.GRPCDataRuntime import GRPCDataRuntime; GRPCDataRuntime.is_ready(ctrl_address=0.0.0.0:port_ctrl)
          initialDelaySeconds: 1
          periodSeconds: 5
        env:
        - name: JINA_LOG_LEVEL
          value: debug
        - name: PYTHONUNBUFFERED
          value: "1"
        - name: WORKER_CLASS
          value: "uvicorn.workers.UvicornH11Worker"

